<?php

namespace wock\essentialx;

use pocketmine\plugin\PluginBase;
use pocketmine\Server;
use wock\essentialx\{Commands\AnvilCommand,
    Commands\BackCommand,
    Commands\BanCommand,
    Commands\BanIPCommand,
    Commands\BanLookupCommand,
    Commands\CondenseCommand,
    Commands\ExpCommand,
    Commands\FeedCommand,
    Commands\FlyCommand,
    Commands\GamemodeCommand,
    Commands\GiveCommand,
    Commands\HealCommand,
    Commands\ItemDBCommand,
    Commands\KitCommand,
    Commands\NearCommand,
    Commands\ReloadCommand,
    Commands\SpawnCommand,
    Commands\TempBanCommand,
    Enchantments\BaneOfArthropodsEnchantment,
    Enchantments\FortuneEnchantment,
    Enchantments\LootingEnchantment,
    Enchantments\SmiteEnchantment,
    Events\EssentialsXEvent,
    Commands\AfkCommand,
    Events\VanillaEnchanatmentEvent};
use pocketmine\utils\TextFormat;

class EssentialsX extends PluginBase {

    /** @var EssentialsX */
    private static EssentialsX $instance;

    public const NOPERMISSION = TextFormat::DARK_RED . "You do not have access to that command.";
    
    public function onLoad(): void
    {
        self::$instance = $this;
        $enchants = [
            new FortuneEnchantment(),
            new LootingEnchantment(),
            new SmiteEnchantment(),
            new BaneOfArthropodsEnchantment(),
            new DepthStriderEnchantment
        ];
        foreach ($enchants as $enchant) {
            EnchantmentIdMap::getInstance()->register($enchant->getMcpeId(), $enchant);
            StringToEnchantmentParser::getInstance()->register($enchant->getId(), fn() => $enchant);
        }
    }
    public function onEnable(): void
    {
        $this->saveDefaultConfig();
        $this->unregisterCommands();
        $this->registerCommands();
        $this->registerEvents();
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public function registerCommands() {
        $this->getServer()->getCommandMap()->registerAll("essentialsx", [
            new AfkCommand($this),
            new AnvilCommand($this),
            new BackCommand($this, new EssentialsXEvent()),
            new BanCommand($this),
            new ExpCommand($this),
            new GamemodeCommand(),
            new FlyCommand(),
            new SpawnCommand($this),
            new BanIPCommand($this),
            new CondenseCommand($this),
            new ReloadCommand(),
            new KitCommand(),
            new HealCommand(),
            new BanLookupCommand($this).
            new NearCommand($this),
            new FeedCommand(),
            new ItemDBCommand(),
            new GiveCommand(),
            new TempBanCommand($this),
        ]);
    }

    public function unregisterCommands() {
        Server::getInstance()->getCommandMap()->unregister(Server::getInstance()->getCommandMap()->getCommand("ban"));
        Server::getInstance()->getCommandMap()->unregister(Server::getInstance()->getCommandMap()->getCommand("ban-ip"));
        Server::getInstance()->getCommandMap()->unregister(Server::getInstance()->getCommandMap()->getCommand("gamemode"));
    }

    public function registerEvents() {
        $pluginMngr = $this->getServer()->getPluginManager();

        $pluginMngr->registerEvents(new EssentialsXEvent(), $this);
        $pluginMngr->registerEvents(new VanillaEnchanatmentEvent(), $this);
    }

    public static function getInstance(): EssentialsX
    {
        return self::$instance;
    }

}

